Ensure compatibility with Python 3.11
- Replace deprecated `getargspec()` with `getfullargspec()`
- Replace deprecated `formatargspec()` with custom implementation

Copied `formatconfigargspec()` from sicherha/powerline@6238d9e8 after a number
of failed attempts to use `inspect.signature` or `Signature` directly as
suggested.

Resolves errors in Python 3.11 & warnings in 3.10:
```
$ python3.11 zdeskcfg.py
Traceback (most recent call last):
File "zdeskcfg/zdeskcfg.py", line 161, in <module>
@configure()
^^^^^^^^^^^
File "zdeskcfg/zdeskcfg.py", line 36, in __call__
tgt_argspec = inspect.getargspec(tgt_func)
^^^^^^^^^^^^^^^^^^
AttributeError: module 'inspect' has no attribute 'getargspec'. Did you mean: 'getargs'?

$ python3.10 zdeskcfg.py
zdeskcfg/zdeskcfg.py:36: DeprecationWarning: inspect.getargspec() is deprecated since Python 3.0, use inspect.sign$
tgt_argspec = inspect.getargspec(tgt_func)
zdeskcfg/zdeskcfg.py:42: DeprecationWarning: inspect.getargspec() is deprecated since Python 3.0, use inspect.sign$
argspec = inspect.getargspec(tgt_func)
zdeskcfg/zdeskcfg.py:53: DeprecationWarning: `formatargspec` is deprecated since Python 3.5. Use `signature` and t$
signature = inspect.formatargspec(
zdeskcfg/zdeskcfg.py:66: DeprecationWarning: `formatargspec` is deprecated since Python 3.5. Use `signature` and t$
newsignature = inspect.formatargspec(*newargspec)[1:-1]
```